version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: project-mongo-1
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: project-backend-1
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file:
      - .env   # 👈 aquí se carga tu clave de OpenWeather
    environment:
      - MONGO_URL=mongodb://mongo:27017/clima
    volumes:
      - ./backend/logs:/app/logs
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: project-frontend-1
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo-data:
